# Generated by Django 4.2.3 on 2023-07-29 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Не указано', max_length=200)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='Surfaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Surface',
                'verbose_name_plural': 'Surfaces',
            },
        ),
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_code', models.CharField(max_length=100)),
                ('light', models.CharField(max_length=20)),
                ('side', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200, null=True)),
                ('latitude', models.DecimalField(decimal_places=13, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=13, max_digits=16)),
                ('scheme', models.URLField()),
                ('price', models.FloatField(blank=True, null=True)),
                ('digital', models.PositiveIntegerField(blank=True, null=True)),
                ('grp', models.FloatField(blank=True, null=True)),
                ('ots', models.FloatField(blank=True, null=True)),
                ('code_espar', models.CharField(blank=True, max_length=30, null=True)),
                ('sales_july', models.CharField(blank=True, max_length=400, null=True)),
                ('sales_august', models.CharField(blank=True, max_length=400, null=True)),
                ('sales_september', models.CharField(blank=True, max_length=400, null=True)),
                ('sales_october', models.CharField(blank=True, max_length=400, null=True)),
                ('sales_november', models.CharField(blank=True, max_length=400, null=True)),
                ('sales_december', models.CharField(blank=True, max_length=400, null=True)),
                ('products', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('technic', models.URLField(blank=True, null=True)),
                ('price_montage', models.PositiveIntegerField(blank=True, null=True)),
                ('price_remontage', models.FloatField(blank=True, null=True)),
                ('permission_to', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_excel_db.cities')),
                ('material', models.ForeignKey(default='Не указано', on_delete=django.db.models.deletion.SET_DEFAULT, to='import_excel_db.materials')),
                ('surface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_excel_db.surfaces')),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
            },
        ),
    ]
