# Generated by Django 4.2.3 on 2023-07-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_excel_db', '0002_alter_boards_material_alter_materials_description'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='boards',
            constraint=models.UniqueConstraint(fields=('in_code', 'surface'), name='code_surface'),
        ),
    ]
