# Generated by Django 4.2.3 on 2023-07-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_excel_db', '0002_alter_cities_options_alter_materials_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='longitude',
            field=models.DecimalField(decimal_places=13, max_digits=16),
        ),
    ]
