# Generated by Django 4.2.3 on 2023-07-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_excel_db', '0004_alter_boards_surface_alter_boards_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boards',
            unique_together=set(),
        ),
    ]
